name: xirfadsan_receipt
description: Receipt UI + PDF + Share
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.1
  image_picker: ^1.0.4  # For image upload
  iconsax: 0.0.8       # For icons
  url_launcher: ^6.2.2
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Comment out fonts for now to test
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf